---
- name: call API from Satellite
  hosts: localhost
  gather_facts: no
  vars:
    satelliteurl: satellite.ravi.local
    client: nn1.ravi.local

  tasks:
    - name: get modules for given host from satellite 
      uri:
       # url: https://{{ satelliteurl }}/api/v2/hosts/{{ client }}
        url: https://{{ satelliteurl }}/api/v2/hosts
        method: GET 
        user: restapi-user1 
        password: 'password'
        force_basic_auth: yes 
        validate_certs: no

      register: restdata

    - name: output rest data
      debug: 
        #var: item.name
        msg: "{{ restdata.json  }}" 
#      with_items : "{{restdata.json.results}}" 
#      when: item.name | regex_search('nn.*' )


    - name: write to file
      local_action:
        module: lineinfile 
        line:  "{{item.name}}, {{item.subscription_facet_attributes.last_checkin}}"
        state: present
        create: True
        dest: /tmp/test.out
      with_items : "{{restdata.json.results}}"
      #when: not item.name | regex_search('nn.*' )



