---
- name: call API from Satellite
  hosts: localhost
  gather_facts: no
  vars:
    satelliteurl: satellite.ravi.local
    client: nn1.ravi.local

  tasks:
    - name: get modules for given host from satellite 
      uri:
       # url: https://{{ satelliteurl }}/api/v2/hosts/{{ client }}
        url: https://{{ satelliteurl }}/api/v2/hosts
        method: GET 
        user: restapi-user1 
        password: 'password'
        force_basic_auth: yes 
        validate_certs: no
      register: restdata
      tags: get_data

    - name: get current date
      command: 'date +%Y-%m-%d'
      register: current_date

    - name: remove host file 
      copy:
          content: ""
          dest: /tmp/test.out
          force: yes
      
    - debug:
        var:  item.subscription_facet_attributes.last_checkin  
        #        var:  rest_data.json
      when: item.subscription_facet_attributes.last_checkin != current_date.stdout
      with_items : "{{restdata.json.results}}"
        

    #- name: write to file
    #  local_action:
    #    module: lineinfile 
    #    line:  "{{item.name}}"
    #    state: present
    #    create: True
    #    dest: /tmp/test.out
    #  with_items : "{{restdata.json.results}}"
    #  when: item.subscription_facet_attributes.last_checkin != current_date.stdout
    #  tags: dddd



